# Generated by Django 3.2.3 on 2021-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
    ]
