# Generated by Django 3.2.3 on 2021-06-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopCore', '0014_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Изображение товара'),
        ),
    ]
